name: Daily Check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  dailycheck:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Running the scheduled task"
